publishDir = ".."
baseurl = "https://ubiratansoares.github.io/"
copyright = "Some rights reserved - 2017"
languagecode = "en-US"
paginate = 5
pluralizelisttitles = false
theme = "casper"
title = "Ubiratan Soares"

[[menu.main]]
name = "Github"
url = "https://github.com/ubiratansoares"
weight = 100

[[menu.main]]
name = "Tweets"
url = "https://twitter.com/ubiratansoares"
weight = 101


[params]
author = "Ubiratan Soares"
authorlocation = "São Paulo, Brasil"
authorwebsite = "http://ubiratansoares.github.io"
bio = "Software Engineer. Curious guy."
description = "Opiniões sobre tecnologia, desenvolvimento de software e mais"
githubName = "ubiratansoares"
twitterName = "ubiratansoares"
linkedinName = "ubiratanfsoares"
googleAnalyticsUserID = "UA-17404026-1"
googleAnalyticsUserID = ""
hideHUGOSupport = true
logo = "images/logo.png"
cover = "images/cover-bw.jpg"
[permalinks]
post = "/:slug/"

[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"