baseurl = "https://ubiratansoares.github.io/"
copyright = "Some rights reserved - 2017"
languagecode = "en-US"
paginate = 5
pluralizelisttitles = false
publishDir = ".."
theme = "casper"
title = "Ubiratan Soares"
[[menu.main]]
name = "Tweets"
url = "https://twitter.com/ubiratanfsoares"
weight = 101
[[menu.main]]
name = "Github"
url = "https://github.com/ubiratansoares"
weight = 100
[params]
author = "Ubiratan Soares"
authorlocation = "São Paulo, Brasil"
authorwebsite = "https://ubiratansoares.github.io"
bio = "Software Engineer. Curious guy."
cover = "images/cover-bw.jpg"
description = "Technology, software engineering and more"
githubname = "ubiratansoares"
googleanalyticsuserid = "UA-17404026-1"
hidehugosupport = true
linkedinname = "ubiratanfsoares"
logo = "images/logo.png"
twittername = "ubiratanfsoares"
[permalinks]
post = "/:slug/"
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
